---
- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/s-osa/dotfiles.git
    dest: '{{ansible_env.HOME}}/src/github.com/s-osa/dotfiles'
- name: Generate dotfile symlinks
  ansible.builtin.file:
    src: '{{ansible_env.HOME}}/src/github.com/s-osa/dotfiles/home/{{item.path}}'
    dest: '{{ansible_env.HOME}}/{{item.path}}'
    state: link
    force: yes
  with_items:
    - path: '.btt_autoload_preset.json'
    - path: '.config'
    - path: '.gitconfig'
    - path: '.gitconfig.agrigate'
    - path: '.gitignore'
    - path: '.ideavimrc'
    - path: '.tmux.conf'
    - path: '.vimrc'
- name: Copy sample files to be edited and not managed by dotfiles repo
  ansible.builtin.copy:
    src: '{{ansible_env.HOME}}/src/github.com/s-osa/dotfiles/home/{{item.path}}.sample'
    dest: '{{ansible_env.HOME}}/{{item.path}}'
    force: no
  with_items:
    - path: '.zprofile'
    - path: '.zshrc'
