---
- name: Generate directories
  file:
    path: "~/screenshots"
    state: directory
- name: Set 'Apple Global Domain' config
  osx_defaults:
    host: "{{ item.host | default() }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - key: ApplePressAndHoldEnabled
      type: bool
      value: false
    - key: AppleTemperatureUnit
      type: string
      value: Celsius
    - key: AppleShowAllExtensions
      type: bool
      value: true
    - key: com.apple.trackpad.scaling
      type: float
      value: 3
    - key: com.apple.trackpad.scrolling
      type: float
      value: 0.5881999999999999
    - key: InitialKeyRepeat
      type: float
      value: 15
    - key: KeyRepeat
      type: float
      value: 2
- name: Set com.apple domain config
  osx_defaults:
    host: "{{ item.host | default() }}"
    domain: "com.apple.{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value | default() }}"
  register: defaults_out
  with_items:
    - domain: dock
      key: mineffect
      type: string
      value: scale
    - domain: dock
      key: mru-spaces
      type: bool
      value: false
    - domain: dock
      key: orientation
      type: string
      value: right
    - domain: screencapture
      key: location
      type: string
      value: "~/screenshots"
    - domain: screencapture
      key: show-thumbnail
      type: bool
      value: false
    - domain: Terminal
      key: "Default Window Settings"
      type: string
      value: Pro
    - domain: dock
      key: tilesize
      type: float
      value: 40
