---
- name: Update homebrew
  homebrew:
    update_homebrew: yes
- name: Install homebrew packages
  homebrew:
    name: '{{item.name}}'
    state: '{{item.state | default("present")}}'
  with_items:
    - name: ffmpeg
    - name: gh
    - name: ghq
    - name: git
    - name: mas # Install App Store apps from CLI
    - name: peco
    - name: tmux
    - name: tree
    - name: vim
    - name: watch
- name: Install homebrew cask packages
  community.general.homebrew_cask:
    name: '{{item.name}}'
    state: present
    install_options: 'appdir=/Applications'
    accept_external_apps: true
  with_items:
    - name: 1password
    - name: alacritty
    - name: alfred
    - name: anki
    #- name: atok (installed app does not work)
    - name: bettertouchtool
    - name: choosy
    - name: discord
    - name: dropbox
    - name: firefox
    - name: google-chrome
    - name: jetbrains-toolbox
    - name: karabiner-elements
    - name: obsidian
    - name: slack
    - name: spotify
    - name: swinsian
    - name: tageditor
    - name: todoist
    - name: xld # X Lossless Decoder
    #- name: zoom
- name: Install App Store apps
  community.general.mas:
    id:
      - 1452453066 # Hidden Bar
      - 539883307 # LINE
    state: present
